alwaysDay: true

changeInventory: true
changeWeather: true

chat-globalSyntax: '%player% > %message%'
chat-localSyntax: '%player% > %message%'
chat-globalMessage: '&8[&6G&8] '
chat-localMessage: '&8[&aL&8] '
chat-cooldown: 3

donatorsEnabled: true

dropItem: true

fallDamage: true

keepInventory: true

lobby: true

oldPvP: true

tablistTag-header: '&fОнлайн игроков: &a%online% &fиз &a%onlineMAX%'
tablistTag-footer: '&e&lFLUXMBER.RU'
tablistTag:
    PREFIX-DEVELOPER: '&f '
    PREFIX-ADMIN: '&f '
    PREFIX-YOUTUBE: '&f '
    PREFIX-CURATORBUILDER: '&f '
    PREFIX-BUILDER: '&f '
    PREFIX-CURATORMODERATOR: '&f '
    PREFIX-MODERATOR: '&f '
    PREFIX-HELPER: '&f '
    PREFIX-FLUX: '&f '
    PREFIX-DIAMOND: '&f '
    PREFIX-EMERALD: '&f '
    PREFIX-GOLD: '&f '
    PREFIX-IRON: '&f '
    PREFIX-COAL: '&f '
    PREFIX-DEFAULT: '&f'
    NAME-DEVELOPER: DEVELOPER
    NAME-ADMIN: ADMIN
    NAME-YOUTUBE: YOUTUBE
    NAME-CURATORBUILDER: CURATORBUILDER
    NAME-BUILDER: BUILDER
    NAME-CURATORMODERATOR: CURATORMODERATOR
    NAME-MODERATOR: MODERATOR
    NAME-HELPER: HELPER
    NAME-FLUX: FLUX
    NAME-DIAMOND: DIAMOND
    NAME-EMERALD: EMERALD
    NAME-GOLD: GOLD
    NAME-IRON: IRON
    NAME-COAL: COAL
    NAME-DEFAULT: DEFAULT
    NAME-DEFAULT: DEFAULT
